spring:
  profiles:
    #激活开发环境
    active: dev
  messages:
    basename: i18n/Messages,i18n/Pages
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  config: classpath:log4j2.yml
swagger:
  enabled: true
  base-package: com.dr.code.diff.controller
##日志配置
#logging:
#  config: classpath:log4j2.yml
#shiro:
#  loginUrl: /view/sys/user/login
#  successUrl: /view/sys/index
#  unauthorizedUrl: /view/sys/unauthorized
#  sessionManager:
#    sessionIdUrlRewritingEnabled: false
git:
  userName: rayduan
  password: $$$$$$!
  local:
    base:
      dir: D:\git-test
  ssh:
    priKey: C:\Users\mylocl/.ssh/id_rsa.
svn:
  userName: admin
  password: 123456
  local:
    base:
      dir: D:\svn-test
server:
  port: 8085
  servlet:
    session:
      timeout: 3600
#jenkins:
#  url: http://192.168.80.128:8081
#  userName: admin
#  password: 1
---
server:
  port: 8084
spring:
  profiles: test
